# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='user',
        ),
    ]
